version: '3.1'
services:
  mongodb:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - myvolume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test@123
    networks:
      - mynetwork
    hostname: mongocontainer
  todoapp:
    image: ayushi01304/nodeimg:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  myvolume:

